networks:
  frontend: # Name of the network
    external: true # Set to true to use an existing network
  backend:
    external: true

services:
  db:
    image: mariadb:latest
    container_name: pureftpd-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    environment:
      TZ: Europe/Madrid
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: pureftpd
      MYSQL_USER: $[USER]
      MYSQL_PASSWORD: $[PASS]
    networks:
      - backend

  pureftpd:
    image: crazymax/pure-ftpd
    container_name: pureftpd
    restart: always
    depends_on:
      - db
    volumes:
      - ./data/:/data/
      - ./$[USER]:/home/$[USER]/
    environment:
      TZ: Europe/Madrid
      AUTH_METHOD: mysql
    networks:
      - frontend
      - backend
    ports:
      - "2100:2100"
      - "30000-30009:30000-30009"